import {persisted} from "svelte-local-storage-store";

export const DEFAULT = {
  profile: [],
  profile_toggle_value: "real_time",
  runner: {},
  runner_path: null,
  federates: [],
  cores: [],
  systeminfo: {},
  graphs: {},
  publications: [],
  inputs: [],
  table: [],
  table_columns: [],
  cores_columns: [
    {
      field: "id",
      sortName: "id",
      title: "ID",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "name",
      sortName: "name",
      title: "Name",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "address",
      sortName: "address",
      title: "Address",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
  ],
  federates_columns: [
    {
      field: "id",
      sortName: "id",
      title: "ID",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "name",
      sortName: "name",
      title: "Name",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "core_name",
      sortName: "core_name",
      title: "Core Name",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
  ],
  inputs_columns: [
    {
      field: "id",
      sortName: "id",
      title: "ID",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "source_name",
      sortName: "source_name",
      title: "Source",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "target_name",
      sortName: "target_name",
      title: "Target",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
  ],
  publications_columns: [
    {
      field: "id",
      sortName: "id",
      title: "ID",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "name",
      sortName: "name",
      title: "Name",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "source_name",
      sortName: "source_name",
      title: "Source",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
    {
      field: "target_name",
      sortName: "target_name",
      title: "Target",
      show: true,
      sort: "ascending",
      sortColor: "#fff",
      sortActive: true,
      text_center: false,
    },
  ],
};

const createHelicsStore = () => {
  const state = persisted('helicsDataStore', DEFAULT);

  return {
    ...state
  }
}

// export const data = storage("data", DEFAULT);
export const data = createHelicsStore();
