exclude: ^(helics-src/|helics-src\.downloaded/)

ci:
  autoupdate_branch: "main"

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        args:
          [
            "--line-length=100",
            "--target-version=py311",
            "--target-version=py312",
            "--target-version=py313",
            "--target-version=py314",
          ]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        args:
          [
            "--line-length=100",
            "--target-version=py311",
            "--target-version=py312",
            "--target-version=py313",
            "--target-version=py314",
          ]
        additional_dependencies: [black==26.5.1]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.51"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
        additional_dependencies:
          - build
          - ninja
          - scikit-build-core
          - setuptools-scm
