"""Build-time version provider for the pyhelics distribution.

The Python package and the bundled native library are released together.  Keep
their versions in sync by using ``helics_version.cmake`` as the single source
of truth instead of deriving the wheel version from the pyhelics Git history.
"""

from __future__ import annotations

import re
from pathlib import Path


_VERSION_PATTERN = re.compile(
    r"set\s*\(\s*HELICS_VERSION\s+(?P<version>[0-9]+\.[0-9]+\.[0-9]+)\s*\)",
    re.IGNORECASE,
)


def _read_version() -> str:
    version_file = Path(__file__).with_name("helics_version.cmake")
    match = _VERSION_PATTERN.search(version_file.read_text(encoding="utf-8"))
    if match is None:
        raise RuntimeError(f"Could not find HELICS_VERSION in {version_file}")
    return match.group("version")


def _write_version_file(version: str) -> None:
    version_file = Path(__file__).with_name("helics") / "_version.py"
    major, minor, patch = (int(part) for part in version.split("."))
    version_file.write_text(
        "# Generated by pyhelics build metadata; do not edit.\n"
        f"__version__ = version = {version!r}\n"
        f"__version_tuple__ = version_tuple = ({major}, {minor}, {patch})\n"
        "__commit_id__ = commit_id = None\n",
        encoding="utf-8",
    )


def dynamic_metadata(field: str, _settings: dict[str, str]) -> str:
    """Return the package version and refresh ``helics/_version.py``."""

    if field != "version":
        raise ValueError("This provider only supplies the project version")

    version = _read_version()
    _write_version_file(version)
    return version
