name: CI - CLI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure history is present for automatic versioning
      - uses: actions/setup-node@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools cffi
      - name: Build NPM
        run: |
          cd helics_cli_extras/client
          npm install
          npm run build
          cp -r build ../helics_cli_extras/static
      - name: Build the web interface first
        run: |
          cd helics_cli_extras
          pip install .
      - name: Download helics library and run pip install
        run: |
          DOWNLOAD_BINARIES=1 pip install ".[cli]"
      - name: Run Server
        run: |
          helics server &
          sleep 5
          curl http://localhost:5000
          kill %+
      - name: Run Observer
        run: |
          mkdir db
          helics observer &
          sleep 5
          kill %+