name: CI - Web

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip install wheel setuptools cffi
      - name: Build the web interface first
        run: |
          cd helics_web
          pip install .
      - name: Download helics library and run pip install
        run: |
          python setup.py download
          python setup.py build_ext
          pip install -e ".[cli]"
      - name: Run CLI
        run: |
          helics server &
          sleep 5
          kill %+
