name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      # TODO compile the ci/cd.yml files? Use pypa/cibuildwheel@v2.16.5 to build wheels, then install and run?
      - name: Download helics library and run pip install
        run: |
          python setup.py download
          python setup.py build_ext
          pip install -e ".[tests]"
      - name: Generate coverage report
        run: |
          pytest -vvv --cov=./ --cov-report=xml:unit.coverage.xml
      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./unit.coverage.xml
          flags: unit
          env_vars: PYTHON
          name: codecov-unit
          fail_ci_if_error: false
