name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure history is present for automatic versioning
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          pip install ".[cli,docs]"
        env:
          DOWNLOAD_BINARIES: 1
      - name: Copy README.md
        run: |
          cp README.md docs/index.md
      - run: mkdocs build
      - name: Github Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
